from __future__ import annotations

import logging
from typing import Any, Optional, List
import time

from pyfedappwrap.engine.config.system_config import FLNetDPSettings, FLNetSMPCSettings
from pyfedappwrap.engine.federated.models import FLNetDataPackageDTO
from pyfedappwrap.engine.service.controller.common import FLNetCommunicator

logger = logging.getLogger(__name__)


class FLNetCommunicatorClient(FLNetCommunicator):
    """Communicator for the client side of a federated run.

    Client developers interact with these methods:
    - ``send_data_to_aggregator``   — submit local training data to an aggregator
    - ``await_data_from_aggregator``— wait for the aggregated result
    - ``send_data_to_client``       — send a peer-to-peer message to other clients
    - ``await_data_from_clients``   — receive peer-to-peer messages from other clients
    """

    def send_data_to_aggregator(
        self,
        data: Any,
        aggregator_name: str,
        communication_id: Optional[str] = None,
        smpc: Optional[FLNetSMPCSettings] = None,
        dp: Optional[FLNetDPSettings] = None,
    ) -> str:
        """Send local training data to the specified aggregator.

        Args:
            data: The local model update or training result to submit.
            aggregator_name: Name of the aggregator that should receive this data.
                This field is required — there is no implicit default.
            communication_id: Optional identifier for this communication round.
                If None, an automatic ID is generated by the controller.
            smpc: Optional SMPC settings for secure multi-party computation.
            dp: Optional differential-privacy settings.

        Returns:
            The communication_id used for this submission.
        """
        return self._send_to_aggregator(
            data=data,
            aggregator_name=aggregator_name,
            communication_id=communication_id,
            smpc=smpc,
            dp=dp,
        )

    def send_data_to_clients(
        self,
        data: Any,
        to: List[str],
        communication_id: str,
        dp: Optional[FLNetDPSettings] = None,
    ) -> str:
        """Send a peer-to-peer message directly to one or more other clients.

        Args:
            data: The payload to send.
            to: List of recipient client IDs. Must not include the aggregator/
                coordinator ID — P2P messages cannot be addressed to the aggregator.
            communication_id: Required identifier for this P2P exchange.
                Automatic comm IDs are not supported for peer-to-peer messages.
            dp: Optional differential-privacy settings.

        Returns:
            The communication_id used.

        Raises:
            ValueError: If ``to`` is empty.
            ValueError: If ``to`` contains the aggregator/coordinator ID.
        """
        if self.aggregator_id and self.aggregator_id in to:
            raise ValueError(
                f"Cannot send a peer-to-peer message to the aggregator/coordinator "
                f"({self.aggregator_id!r}). Use send_data_to_aggregator instead."
            )
        return self._send_to_clients_p2p(
            data,
            communication_id=communication_id,
            to=to,
            dp=dp,
        )

    def await_data_from_aggregator(
        self,
        aggregator: str,
        communication_id: Optional[str] = None,
        data_type: Any = None,
    ) -> FLNetDataPackageDTO:
        """Wait for the aggregated result from the specified aggregator.

        Args:
            aggregator: Name of the aggregator to receive from.
            communication_id: If given, wait for that specific round's result.
                If None, the newest available result with an automatic communcation id
                is returned and all older automatic rounds for this aggregator are discarded.
            data_type: Optional type hint for deserialising the payload data.

        Returns:
            The received data package containing the aggregated result and metadata.
            Only ever contains a single package
            - if no communication_id is given, the newest package with an automatically
            generated comm ID is returned.
            - if a communication_id is given, the package with that ID is returned.

        Raises:
            TimeoutError: If the deadline passes without receiving a result.
        """
        poll_count = 0
        deadline = time.monotonic() + self.timeout
        while poll_count < self.max_polls:
            package = self._receive_from_aggregator_package(
                aggregator_name=aggregator,
                communication_id=communication_id,
                data_type=data_type,
            )
            if package:
                return package
            else:
                poll_count += 1
                if not self._wait_before_next_receive(
                    poll_count=poll_count,
                    communication_id=communication_id,
                    from_clients=[self.aggregator_id] if self.aggregator_id else None,
                    deadline=deadline,
                ):
                    break

        raise TimeoutError(
            f"Did not receive data from aggregator {aggregator!r} "
            f"after {self.max_polls} polls with interval {self.poll_interval}s."
        )

    def await_data_from_clients(
        self,
        from_clients: List[str],
        communication_id: str,
        min_packages_per_round: int = 1,
        data_type: Any = None,
    ) -> list[FLNetDataPackageDTO]:
        """Wait for peer-to-peer messages from the specified clients.

        Args:
            from_clients: List of client IDs whose messages to wait for.
            communication_id: Required identifier for this P2P exchange.
                Automatic comm IDs are not supported for peer-to-peer messages —
                both sender and receiver must agree on the same explicit ID.
            min_packages_per_round: Minimum number of packages requested here.
            One client may send multiple packages
            data_type: Optional type hint for deserialising the payload data.

        Returns:
            List of received data packages, one per sender in ``from_clients``.

        Raises:
            TimeoutError: If fewer packages than expected arrive before the deadline.
        """
        if len(from_clients) == 0:
            raise ValueError("from_clients must contain at least one client ID.")

        poll_count = 0
        deadline = time.monotonic() + self.timeout
        complete_packages: list[FLNetDataPackageDTO] = []
        while poll_count < self.max_polls:
            grouped_packages = self._receive_from_clients_grouped(
                min_packages_per_round=min_packages_per_round,
                from_clients=from_clients,
                to_aggregator=None,
                communication_id=communication_id,
                data_type=data_type,
            )

            if communication_id in grouped_packages:
                complete_packages.extend(grouped_packages[communication_id])
            if len(complete_packages) >= len(from_clients):
                return complete_packages

            poll_count += 1
            if not self._wait_before_next_receive(
                poll_count=poll_count,
                communication_id=communication_id,
                from_clients=from_clients,
                deadline=deadline,
            ):
                break
        return complete_packages

    def aggregate(
        self,
        data: Any,
        aggregator_name: str,
        communication_id: Optional[str] = None,
        data_type: Any = None,
        smpc: Optional[FLNetSMPCSettings] = None,
        dp: Optional[FLNetDPSettings] = None,
    ) -> FLNetDataPackageDTO:
        """Send local data to the aggregator and wait for the aggregated result.

        Args:
            data: The local model update or training result to submit.
            aggregator_name: Name of the aggregator that should receive this data.
            communication_id: Optional identifier for this communication round.
                If None, an automatic ID is generated by the controller.
            data_type: Optional type hint for deserialising the payload data.
            smpc: Optional SMPC settings for secure multi-party computation.
            dp: Optional differential-privacy settings.

        Returns:
            The received data package containing the aggregated result and metadata.
        """
        used_comm_id = self.send_data_to_aggregator(
            data=data,
            aggregator_name=aggregator_name,
            communication_id=communication_id,
            smpc=smpc,
            dp=dp,
        )
        logger.info("[CLIENT %s] sent to aggregator %r; now awaiting broadcast with comm_id=%r",
                    self.client_id, aggregator_name, used_comm_id)
        result = self.await_data_from_aggregator(
            aggregator=aggregator_name,
            communication_id=used_comm_id,
            data_type=data_type,
        )
        logger.info("[CLIENT %s] received aggregated result for comm_id=%r", self.client_id, used_comm_id)
        return result
