config:
  hyperparams:
  - default: ''
    description: The row to assign the file to.
    maxValue: null
    minValue: null
    name: result_mapping
    options:
    - prefix
    - suffix
    - filetype
    - name
    - schema_id
    pattern: null
    type: CATEGORICAL
  - default: ''
    description: The row to assign the file to.
    maxValue: null
    minValue: null
    name: input_mapping
    options:
    - prefix
    - suffix
    - filetype
    - name
    - schema_id
    pattern: null
    type: CATEGORICAL
  input:
  - delimiter: null
    description: Input for the transformationen, autogen
    hasHeader: true
    indexCol: 0
    maxValue: null
    minValue: null
    mode: null
    name: input
    required: false
    shape: null
    tabularSchema: null
    type: CSV
  output:
  - delimiter: null
    description: output for the transformationen, autogen
    hasHeader: null
    indexCol: null
    maxValue: null
    minValue: null
    mode: null
    name: output
    required: false
    shape: null
    tabularSchema: null
    type: CSV
info:
  longDescription: null
  name: BioStatProject
  shortDescription: PoSyMed4U BioStatProject
  slug: biostatproject
  sourceUrl: https://github.com/FeatureCloud/fc-random-forest
  type: ANALYSIS
